### ISSUE TITLE
Use new zoom levels from backend

### ISSUE THREAD

**Issue by alexkiro** [ogorlab/ogor-frontend#67]
This will solve two separate issues:

 - The new raster images at the highest zoom level are far too large to be used as thumbnails, we should use the lowest zoom level to save bandwidth and increase app speed 
 - Change in the backend for zoom levels are backwards incompatible, so the frontend needs to be adjusted

## TODO

 - [x] Use lowest zoom level for thumbnails in home page
 - [x] Use lowest zoom level for thumbnails in parcel history
 - [x] Use lowest zoom level in the observation details page
 - [x] Use the highest zoom levels in the parcel compare page 
 - [x] Use the highest zoom levels in the observation compare page 

## Notes 

 - Needed because of the changes in https://github.com/ogorlab/ogor-backend/issues/108
 - For variable zoom level see https://github.com/ogorlab/ogor-frontend/issues/60
